services:
  folio2:
    image: ghcr.io/asano69/folio2:latest
    container_name: folio2
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - folio2.env
    volumes:
      - ./data:/folio2/data
        #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Etc/UTC
      #
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      #networks:
    #  - traefik_net
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.folio2.rule=Host(`folio2.app.internal`)
#volumes:
#  data:

#networks:
#  traefik_net:
#    external: true

